---
title: "Material overview"
---

## 📚 General references


The following textbooks offer a good general reference to the course
content, and I think its a good idea to read into these books in a 
general way. Moreover, I often point to chapters in the respective 
session pages.

- Wickham, H., Çetinkaya-Rundel, M., & Grolemund, G. (2023). *R for data science: Import, tidy, transform, visualize, and model data* (2nd edition). O'Reilly. [https://r4ds.hadley.nz/](https://r4ds.hadley.nz/)

- Ismay, C., & Kim, A. Y.-S. (2020). *Statistical inference via data science: A ModernDive, into R and the tidyverse*. CRC Press, Taylor and Francis Group. [https://moderndive.com/index.html](https://moderndive.com/index.html)

For more advanced details on the fundamentals of programming in R, I 
recommend the following:

- Wickham, H. (2019). *Advanced R* (Second edition). CRC Press/Taylor & Francis Group. [https://adv-r.hadley.nz/](https://adv-r.hadley.nz/)

For the model-related parts of the lecture I recommend the following book as a further reading reference:

- James, G., Witten, D., Hastie, T., & Tibshirani, R. (2021). An introduction to statistical learning: With applications in R (Second edition). Springer.  [https://www.statlearning.com/](https://www.statlearning.com/) 

::: {.callout-tip collapse="true"}
## Statistics recap
If you want to recap fundamtentals in statistics, check out 
[these tutorials](/content/statrecap.qmd).
:::


## 🔖 Session-specific material



|   Session    | Topic                                                         |       Exercise code                      |
|:------------:|:--------------------------------------------------------------|:----------------------------------------:|
|   [1](#s1)   | [Introduction and installation](/content/material/session01.qmd)         |          `Basics`                        |

